const MICROSERVICIO_HOTEL = "https://localhost:44309/";
const MICROSERVICIO_USUARIO = "https://localhost:44310/";
const MICROSERVICIO_RESERVAS = "https://localhost:44373/";

export { MICROSERVICIO_HOTEL, MICROSERVICIO_USUARIO, MICROSERVICIO_RESERVAS }