const MICROSERVICIO_HOTEL = "https://localhost:44309/";
const MICROSERVICIO_USUARIO = "";
const MICROSERVICIO_RESERVAS = "";

export { MICROSERVICIO_HOTEL, MICROSERVICIO_USUARIO, MICROSERVICIO_RESERVAS }